const types = {
    FILE: {
        UPLOAD: 'FILE.UPLOAD',
        UPLOAD_SUCCESS: 'FILE.UPLOAD_SUCCESS',
        UPLOAD_FAILURE: 'FILE.UPLOAD_FAILURE',
        UPLOAD_PROGRESS: 'FILE.UPLOAD_PROGRESS',
    },
    XPATH: {
        LIST_REQUEST: 'XPATH.LIST_REQUEST',
        LIST_REQUEST_SUCCESS: 'XPATH.LIST_REQUEST_SUCCESS',
        LIST_REQUEST_FAILURE: 'XPATH.LIST_REQUEST_FAILURE',
        QUERY: 'XPATH.QUERY',
        QUERY_SUCCESS: 'XPATH.QUERY_SUCCESS',
        QUERY_FAILURE: 'XPATH.QUERY_FAILURE'
    }
};

export default types;
 